page: JavaScript Calculator
external_link: https://codepen.io/mukobi/full/POGNOV/
description: |
  A fully-functioning four-function caluculator built as a small JavaScript coding challenge. Fortunately, not <i>all</i> of JavaScripts troublesome floating point calculation errors are present in this app due to some clever scripting.