template: categories/games.html
page: games
title: Games - Sticks and Stones Software
description: Various virtual reality, flatscreen, and other games that I've built (or am currently building). The tools used to make these games include Unity, Blender, GIMP, C++, C#, DirectX, OpenGL, and HLSL. Also consider checkout out my <a href="https://www.artstation.com/gabrielmukobi">3D art</a> and <a href="https://gabrielmukobi.com/#portfolio">other portfolios</a>.