template: categories/games.html
page: games
title: Games - Sticks and Stones Software
description: Various virtual reality and flatscreen games that I've built using Unreal Engine, Unity, Blender, GIMP and other tools. Also consider checking out my <a href="https://www.artstation.com/gabrielmukobi">digital 3D art</a> and <a href="https://gabrielmukobi.com/#portfolio">other portfolios</a>.