page: Centrify VR
external_link: https://github.com/mukobi/ball-therapy-vr/releases
description: |
  CentrifyVR is an immersive virtual reality relaxation experience that guides users to become more aware of their movements. This game, inspired by tai chi, places players into a various scenes, such as a sunset sky or starry universe. The player's hands steadily trace out the path of glowing orbs as they perform different and increasingly more complex movements as new levels are reached. 
  <br><br>
  Responsible for: Everything except models and skybox textures.