page: UnSoundBoard
external_link: https://github.com/mukobi/UnSoundBoard
description: |
  I wanted to use a soundboard application to play sounds through a virtual microphone for online D&D with friends, but I couldn't find one that I liked. Most looked ugly, limited the number of sounds, and critically, would not have any randomization of the sounds played.
  <br><br>
  So I made this project in Unreal Engine to address those issues. UnSoundBoard looks clean, it resizes based on the window size, and it allows you to randomly play a sound from many in a particular folder when selecting the soundboard button for that folder.