page: Rogue Starfighter VR
external_link: https://youtu.be/v9J4RfixmcA
description: |
  Rogue Starfighter VR is an immersive virtual reality Star Wars X-wing flight simulator fan-game. In it, the player experiences the full scale of space combat from a galaxy far, far, away behind the controls of an immersive and fully-interactive T-65B X-wing starfighter including buttons, switches, and joysticks that you physically manipulate with your VR hands.
  <br><br>
  Responsible for: Everything except source material, music, most sound effects, and the exterior models of each ship. 