page: Rogue Starfighter VR
external_link: https://youtu.be/v9J4RfixmcA
description: |
  Rogue Starfighter VR (RSVR) is an immersive virtual reality Star Wars X-wing flight simulator fan-game. In it, the player experiences the full scale and power of the space combat from a galaxy far, far, away behind the hand-interactable controls of an immersive and fully-interactive T-65B X-wing starfighter.
  <br><br>
  Responsible for: Everything except music, most sound effects, and the exterior models of each ship. 