page: simply8band
external_link: https://mukobi.github.io/Simply8Band
description: |
  Formerly located at simply8band.com, this website is the official website for the band Simply 8, a rock band from Camas, Washington.

  Approximately 92% of all popular music contains profanity in the lyrics and meaning. Simply 8 members Rachel Higgins, Gabe Mukobi, Soroush Badiei, Zephry Lyne, and Hayden Kane want to write meaningful, pure music in order to be in that 8%. We believe it is this that makes us fresh, interesting, and most importantly, different.