page: simply8band
external_link: https://mukobi.github.io/Simply8Band
description: |
  Formerly located at simply8band.com, this website is the official website for the band Simply 8, my high school rock band.
