page: Nuclear Family Feud,
external_link: https://codepen.io/mukobi/full/ybZVMp/
description: |
  Juniors in Mr. Tomasetti's AP US History class at Camas High School are required to create a research on a decade of US history and creatively present to the rest of the class.

  This is a Family Fued styled game that Gabriel Mukobi used to present his decades project on the 1940s.