page: Nuclear Family Feud
external_link: https://codepen.io/mukobi/full/ybZVMp/
description: |
  Juniors in my high school AP US History class were required to create a research project on a decade of US history and creatively present to the rest of the class.

  This is a Family Feud styled game that I used to present my decades project on the 1940s.
