page: PieWallet
external_link: https://github.com/mukobi/PieWallet
description: |
  PieWallet is a hybrid cryptocurrency wallet and social media web app built in PHP and JavaScript as a freelance project (imagine crypto+Venmo). Building PieWallet required significant knowledge in social networks, API design and public API calls, and blockchain and cryptocurrency.