template: categories/desktop.html
page: desktop
title: Desktop - Gabriel Mukobi Software
description: Some of the desktop software I've developed using technologies like Java, Python, C++, C#, .NET, and XNA.