template: categories/desktop.html
page: desktop
title: Desktop - Gabriel Mukobi Software
description: Find some of the desktop software developed by Gabriel Mukobi Software here. I build for desktop using such technologies as Java, Python, C++, C#, .NET, and XNA.