template: home.html
page: home
title: Film - Gabriel Mukobi
header_title: Films by <br><a href="http://gabrielmukobi.com">Gabriel Mukobi</a>
description: Short films, video essays, and other motion picture works by <a href="http://gabrielmukobi.com">Gabriel Mukobi</a>. If you enjoy these project, also consider viewing my <a href="https://photos.gabrielmukobi.com">photography</a>, <a href="https://www.artstation.com/gabrielmukobi">3D art</a> and <a href="https://gabrielmukobi.com/#portfolio">other portfolios</a>.