page: gabrielmukobi.com
external_link: http://gabrielmukobi.com/
description: |
  The online portfolio for Gabriel Mukobi:  a digital creator who is passionate about virtual reality, games, AI, film, music, 3D art, and photography.
  <br><br>
  On this site, you can find more about Gabe as a person, read or download his resume, find a portfolio of his different projects, view a curriculum vitae, and contact Gabe.