external_link: https://vhil.stanford.edu/projects/2020/vbr-immersion-and-presence/
title: Virtual Becomes Reality - A Stanford VR Experience
description: |
  With Virtual Reality technology now widely available, it’s more important than ever to understand its effects on people and society. Explore highlights of nearly two decades of VR research from Stanford University’s Virtual Human Interaction Lab. Become immersed, and discover how we can use this powerful medium to enhance our everyday lives.
  <br><br>
  I worked on several different virtual reality experiences that constitute this VR film as a Virtual Reality Intensive Training Seminar (VRITS) programmer at the Virtual Human Interaction Lab (VHIL).