page: Levelling Up in AIS Research RE
external_link: https://forum.effectivealtruism.org/posts/S7dhJR5TDwPb5jypG/levelling-up-in-ai-safety-research-engineering
description: |
  A level-based guide for independently up-skilling in AI Safety Research Engineering that aims to give concrete objectives, goals, and resources to help anyone go from zero to hero.
  <br><br>
  Responsible for: Everything, though it draws upon knowledge from others listed in the Sources section.