page: Levelling Up in AIS RE
external_link: https://docs.google.com/document/d/1b83_-eo9NEaKDKc9R3P5h5xkLImqMw8ADLmi__rkLo4
description: |
  A level-based guide for independently up-skilling in AI Research Engineering that aims to give concrete objectives, goals, and resources to help anyone go from zero to hero.
  <br><br>
  Responsible for: Everything, though it draws upon knowledge from others listed in the Sources section.
