page: Societal Adaptation to Advanced AI
external_link: https://arxiv.org/abs/2405.10295
description: |
  A paper describing a complementary AI governance strategy focused on societal adaptation: reducing the possible negative impacts from a given level of advanced AI through adaptive interventions that help society avoid, defend against, and remedy harmful uses.
  <br><br>
  Responsible for: Co-authoring the paper.
