external_link: https://youtu.be/JGp178hxgLI
title: Half Life Alyx VR Interaction Research Proposal
description: |
  Half-Life: Alyx is fantastic, but not many reviewers have talked in-depth about the design decisions around the VR controls of the game.
  <br><br>
  In this brief video essay, I propose why I'm going to dive into the VR interaction design of Alyx to help other developers in VR and beyond.