template: home.html
page: home
title: Gabriel Mukobi Software
description: Gabriel Mukobi Software is my personally-run software development company that develops <a href='games'>games</a>, <a href='web'>websites</a>, <a href='desktop'>desktop software</a>, and <a href='mobile'>mobile applications</a>. As its name implies, Gabriel Mukobi is committed to creating simple yet effective software solutions to interesting problems.