template: home.html
page: home
title: Sticks and Stones Software
description: Sticks and Stones Software is my personally-run software development company that develops <a href='games'>games</a>, <a href='web'>websites</a>, <a href='desktop'>desktop software</a>, and <a href='mobile'>mobile applications</a>. As its name implies, Sticks and Stones is committed to creating simple yet effective software solutions to interesting problems.