page: Twitch Stream Displayer,
external_link: https://codepen.io/mukobi/full/RZXgeY/
description: |
  This Twitch stream displayer allows you to see the status of several popular channels on Twich, an online streaming service. Check out who is streaming, find desciptions of what they are streaming, a click the banners to go to the streams.