template: categories/ai.html
page: ai
header: artificial intelligence
title: AI - Gabriel Mukobi Software
description: |
  Machine learning/deep learning/reinforcement learning/other AI projects with a focus on AI safety, including both technical research projects and some community resources for helping others learn.