template: home.html
page: home
title: Photography - Gabriel Mukobi
header_title: <a href="http://gabrielmukobi.com">Gabriel Mukobi</a> Photography
description: lorem ipsum is a fantastic phrase, but it's not quite as fantatic as "Sphinx of black quartz, judge my vow!" which astonishingly contains all 26 letters of the English Latin alphabet.