external_link: https://youtu.be/z8ff1fSjMmE
title: Don't Panic
description: |
  A young woman tries to stay calm during a period of stress.

  Short film made in 48 hours for the 3rd Sandbox Film Fest, Winter 2020. Festival Awards Won: Best Use of Prompts, Best Actress
  
  A FILM BY: Isabel Benak, Caroline Utz, Gabriel Mukobi
  
  STARRING: Caroline Utz