external_link: https://youtu.be/z8ff1fSjMmE
title: Don't Panic
description: |
  A young woman tries to stay calm during a period of stress.
  <br><br>
  Short film made in 48 hours for the Stanford Film Society's 3rd Sandbox Film Fest in Winter 2020. Festival Awards Won: Best Use of Prompts, Best Actress.
  <br><br>
  A FILM BY: Isabel Benak, Caroline Utz, Gabriel Mukobi
  <br><br>
  STARRING: Caroline Utz