page: Homuncular Flexibility VR
external_link: https://youtu.be/JyJ8WHgIZ40
description: |
  Homuncular Flexibility is a virtual reality experience that seeks to explore the mind's ability to "remap" the roles of the limbs in regards to how they are controlled by the brain for theraputic and psychological applications. In it, the movements of your arms and legs in real life affect your body in different ways in VR. This is a project for Stanford's Virtual Human Interaction Lab (VHIL). 
  <br><br>
  Responsible for: Everything except the lab and robot models.