page: Third Arm VR
external_link: https://youtu.be/sdJuJjC0zDI
description: |
  What if you had a third arm? Would it be useful? How would you control it? In this demo, you control a third arm with various combinations of your headset and two VR controllers, and you can play a button popping game where you must learn mastery of all three of your arms. This is a project for Stanford's Virtual Human Interaction Lab (VHIL).
  <br><br>
  Responsible for: Everything except the lab and character models.