page: Scaffold
external_link: https://www.youtube.com/watch?v=i2yBxHFppUg
description: |
  Simulated Comments from the Alignment Forum For Original Literature Development (SCAFFOLD) is a writing tool that generates comments that are similar to those on the Alignment Forum in order to elevate your AI safety to the next level!
  <br><br>
  Responsible for: Everything sans data collection scripts.