page: Scaffold
external_link: .
description: |
  Simulated Comments from the Alignment Forum For Original Literature Development (SCAFFOLD) is a writing tool that generates LLM comments that are similar to human comments from an online AI research forum by fine-tuning a 6B parameter LLM on those comments.
  <br><br>
  Responsible for: Everything sans data collection scripts.
