page: 2XKO
# external_link: https://www.riotgames.com/en/news/project-l-dev-finding-our-game
external_link: https://2xko.riotgames.com/en-us/
description: |
  2XKO (codenamed Project L) is a 2026 2v2 tag-team fighting game developed by Riot Games and set in the League of Legends Universe.
  <br><br>
  Responsible for: Designing and implementing several core gameplay features as a Software Engineering Intern on the Gameplay team from June-Sept 2021.
