page: Project L
external_link: https://www.riotgames.com/en
description: |
  Project L is an unreleased fighting game made by Riot Games and set in the League of Legends Universe.
  <br><br>
  Responsible for: Designing and implementing several core gameplay features as a Software Engineering Intern on the Gameplay team from June-Sept 2021.