page: Random Quote Generator
external_link: https://codepen.io/mukobi/full/LjexBG/
description: |
  This is a simple but fun app that generates a random quote using the quotesondesign.com quote API. It's very useful for getting some random inspiration, a funny idea, or just something unique said by someone important.