page: Virtual Becomes Reality
external_link: https://vhil.stanford.edu/projects/2020/vbr-immersion-and-presence/
description: |
  Explore highlights of nearly two decades of VR research from Stanford University’s Virtual Human Interaction Lab densely packed into one 20-minute VR experience. Virtual Becomes Reality premiered in June 2020 as part of the Cannes XR festival, is an official selection of the 2020 Tribeca Film Festival, and will soon be released on Steam.
  <br><br>
  Responsible for: Many critical gameplay programming features, fixes, and content improvement earning me 1 of 2 Senior Programmer credits out of more than a dozen people involved with the project. 