page: Virtual Becomes Reality
external_link: https://store.steampowered.com/app/1658530/Virtual_Becomes_Reality_A_Stanford_VR_Experience/
description: |
  Explore highlights of nearly two decades of VR research from Stanford University’s Virtual Human Interaction Lab densely packed into one 20-minute VR experience. Virtual Becomes Reality premiered in June 2020 as part of the Cannes XR festival, is an official selection of the 2020 Tribeca Film Festival, and was released on Steam in June 2021.
  <br><br>
  Responsible for: Many critical gameplay programming features, bug fixes, and content improvements earning Technical Lead and Senior Programmer credits. 