external_link: https://youtu.be/fioK1i_NVcE
title: |
  An Accessible Reality - How Half-Life: Alyx Achieves Universal VR Design
description: |
  What lessons can VR developers take from the interaction system design of Half-Life: Alyx?
  <br><br>
  Let’s explore several of the high-level design strategies Valve used to make Alyx a more accessible, intuitive, and fun VR experience!