page: Star Wars FPS
external_link: https://www.riotgames.com/en/news/project-l-dev-finding-our-game
description: |
  Respawn Entertainment is working on a yet-unreleased first-person shooter title in the Star Wars universe.
  <br><br>
  Responsible for: Designing and implementing several core gameplay features as a Software Engineering Intern on the Gameplay team from June-Sept 2022.