page: Star Wars FPS
external_link: https://www.ea.com/en-gb/news/electronic-arts-and-lucasfilm-games-announce-new-star-wars-titles-from-respawn-entertainment
description: |
  Respawn Entertainment is working on a yet-unreleased first-person shooter title in the Star Wars universe.
  <br><br>
  Responsible for: Designing and implementing several core gameplay features as a Software Engineering Intern on the Gameplay team from June-Sept 2022.