template: categories/web.html
page: web
title: Web - Gabriel Mukobi Software
description: |
  Some of the websites and web apps that I've developed using technologies like HTML5, CSS3, JavaScript, jQuery, React, Flask, Bootstrap, and Wordpress.