template: categories/web.html
page: web
title: Web - Sticks and Stones Software
description: |
  Some of the websites and web apps that I've developed. These sites use tools and technologies like HTML5, CSS3, JavaScript, jQuery, React, Flask, Bootstrap, Wordpress, and responsive design.