page: Pong
external_link: ./Pong/game.html
description: |
  A recreation of the classic game built entirely through JavaScript with the HTML5 canvas (in only 77 lines of HTML!).

  To play, simply move your mouse over the game window.