page: Mukobi Music
external_link: https://music.gabrielmukobi.com/
description: |
  A website for anything musical regarding Gabriel Mukobi. Gabe plays French horn, guitar, trumpet, bass, and keyboard, and he is always trying to learn new things. He has played in several of the Camas High School bands as well as the rock band Simply 8, and currently he is writing, recording, and producing a solo album.

  On this website, you can find information about Gabe's music, his career and groups he's played with, lessons with Gabe, and more.