page: Gabriel Mukobi Software
external_link: https://software.gabrielmukobi.com/
description: |
  Gabriel Mukobi (the website that you are currently viewing) is the site for Gabriel Mukobi Software, a software development company founded and operated by Gabriel Mukobi that develops games, websites, desktop solutions, and mobile applications. As its name implies, Gabriel Mukobi is committed to creating simple yet effective software solutions to interesting problems.